### PR TITLE
Sprint 9 frontend visuals bugfix complete

### LINKED ISSUE #102: Sales Tracker Bar chart not visible to sales rep
<h1/> Description 

When logged into the sales rep account, I was not able to see the Sales Tracker bar chart appear. and there is an error in the console.

<h3/> Steps to Reproduce

- Log into a sales Rep account
- The Sales Tracker does not render
- Click on Month or Year, an error will appear in the console.

<h3/> Screenshots

image

### PR DESCRIPTION
**Pull request by AdrienKamran**
This should close #102.

### CODE REVIEW

File: backend/routes/dashboardVisuals.js [hunk 1]
```diff
@@ -6,10 +6,10 @@ const {
 } = require('../controllers/saleController');
 
 // get authentication middleware
-const { protect } = require('../middleware/auth');
+const { protect, hasRoles} = require('../middleware/auth');
 
 // add .get(protect, getSalesByTime) later
 router.route('/visual3')
-    .get(protect, getSalesByTime)
+    .get(protect, hasRoles('Administration', 'Management', 'Sales Rep', 'Reception'), getSalesByTime)
```
Comment (AbdulSir) [inline backend/routes/dashboardVisuals.js:13]: calling the hasRoles and passing all the roles is redundant. We can just remove that middleware entirely because we do not want to restrict permission to this endpoint

File: backend/routes/sales.js [hunk 2]
```diff
@@ -27,9 +27,9 @@ router.route('/')
 router.route('/:saleId')
   .delete(protect, hasRoles('Administration', 'Management', 'Sales Rep'), createHistory, deleteSale)
   .put(protect, hasRoles('Administration', 'Management', 'Sales Rep'), createEvent, createHistory, updateSale)
-  .get(protect, getSale)
+  .get(protect, hasRoles('Administration', 'Management', 'Sales Rep', 'Reception'), getSale)
```
Comment (AbdulSir) [inline backend/routes/sales.js:30]: Same as above

File: frontend/src/views/pages/Dashboard.vue [hunk 3]
```diff
@@ -51,8 +51,8 @@
           </CCol>
         </CRow>
         <DashboardLineChart
-          v-if="selectedDealership"
-          :dealership="selectedDealership"
+          v-if="selectedDealership || $store.state.auth.role != 'Administration'"
+          :dealership="selectedDealership ? selectedDealership : $store.state.auth.dealership"
```
Comment (AbdulSir) [inline frontend/src/views/pages/Dashboard.vue:55]: This code change seems to be fixing the bug #102

**Review by AbdulSir — CHANGES_REQUESTED** [review]
We can remove the hasRoles method from the routes when all roles are allowed to make a call to a certain endpoint. Also, if we can change the color of the bars in the main big graph to something more subtle (ie.g. shades of blue).

File: backend/routes/dashboardVisuals.js (hunk 1 above)
Comment (AdrienKamran) [reply backend/routes/dashboardVisuals.js]: Resolved!

File: backend/routes/sales.js (hunk 2 above)
Comment (AdrienKamran) [reply backend/routes/sales.js]: Resolved!

File: frontend/src/views/pages/Dashboard.vue (hunk 3 above)
Comment (AdrienKamran) [reply frontend/src/views/pages/Dashboard.vue:55]: Can confirm the above.

**Review by AbdulSir — APPROVED** [review]
The bug is definitely fixed now. However, I was wondering if we can do something about the layout of the bar graph? can we restrict the max-height to a certain value? Because it's taking about 70% of my viewport

image

**Comment by AdrienKamran** [comment]
> The bug is definitely fixed now. However, I was wondering if we can do something about the layout of the bar graph? can we restrict the max-height to a certain value? Because it's taking about 70% of my viewport
> 
> image

I was able to get this fixed by limiting the chart's height to 55% of the viewport's maximum height, see 2803ed801ff0b91198152729cfb264f02474be1b
image

**Review by purplesmurf1998 — APPROVED** [review]

**Comment by AbdulSir** [comment]
I have reviewed this PR and the visuals look great! This branch is ready to be merged
